//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        public int id { get; set; }
        public Nullable<int> MarketId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> Rooms { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string Address { get; set; }
        public Nullable<int> Settlement { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual District District { get; set; }
        public virtual Market Market { get; set; }
        public virtual Owners Owners { get; set; }
        public virtual Settlement Settlement1 { get; set; }
        public virtual Types Types { get; set; }
    }
}
